client_id = "c9d266a38e2f11a1240139974253b3a1"
name = "Skyra Booking"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true
[build]
automatically_update_urls_on_dev = true
[access_scopes]
scopes = "write_products,write_metaobjects,read_metaobjects,write_metaobject_definitions,read_metaobject_definitions,write_app_proxy"
[auth]
redirect_urls = ["https://shopify.dev/apps/default-app-home/auth/callback"]
[app_proxy]
url = "/apps/skyra-booking"
prefix = "apps"
subpath = "skyra-booking"

[webhooks]
api_version = "2026-07"
[[webhooks.subscriptions]]
topics = ["app/uninstalled"]
uri = "/webhooks/app/uninstalled"
[[webhooks.subscriptions]]
topics = ["app/scopes_update"]
uri = "/webhooks/app/scopes_update"
[product.metafields.app.booking_owner_id]
name = "Booking owner ID"
type = "single_line_text_field"
access.admin = "merchant_read"
[product.metafields.app.entitlement_kind]
name = "Booking entitlement kind"
type = "single_line_text_field"
access.admin = "merchant_read"


